apiVersion: v1
kind: Pod
metadata:
  name: docker-image-build
  namespace: jenkins
spec:
  initContainers:
  - name: install-docker
    image: docker:dind
    command: ["sh", "-c", "apk add --no-cache docker"]
    securityContext:
      privileged: true
  containers:
  - name: dind
    image: docker:dind
    imagePullPolicy: Always
    securityContext:
      privileged: true
