apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080        # The service's external port
      targetPort: 8080  # The port your Jenkins app is listening on inside the container
  type: LoadBalancer
