name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set tag variable
        run: echo "TAG=0.5" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag lavi324/git_hub_actions:${{ env.TAG }}

      - name: Push Docker Image
        run: docker push lavi324/git_hub_actions:${{ env.TAG }}
