name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract current version from Docker image tags
        id: extract_version
        run: echo "::set-output name=version::$(docker image inspect --format '{{ index .RepoDigests 0 }}' my-image-name | awk -F ':' '{print $2}')"
      - name: Calculate new version
        id: calculate_version
        run: echo "::set-output name=new_version::$(echo "${{ steps.extract_version.outputs.version }}" | awk -F '.' '{printf "%.1f", $1 + 0.1}')"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lavi324/git_hub_actions:${{ steps.calculate_version.outputs.new_version }}
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push the Docker image to Docker Hub
        run: docker push lavi324/git_hub_actions:${{ steps.calculate_version.outputs.new_version }}

