name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract current version from Docker image tags
        id: extract_version
        run: |
          latest_version=$(docker run --rm lavi324/git_hub_actions:latest echo "v$(awk -F '.' '{printf \"%.1f\", $1 + 0.1}' <<< ${{ steps.extract_version.outputs.version }})")
          echo "::set-output name=latest_version::$latest_version"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lavi324/git_hub_actions:${{ steps.extract_version.outputs.latest_version }}
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push the Docker image to Docker Hub
        run: docker push lavi324/git_hub_actions:${{ steps.extract_version.outputs.latest_version }}
